name: Test Minimal Reusable
on: workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/tmpl_test.yml
    with:
      working_directory: '_sources/Projects/NewsSummarizer'
      script_command: 'echo hello'
      commit_message: 'Test'
      file_pattern: '*.md'
    secrets: inherit
