name: Minimal Reusable
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
jobs:
  draft-content:
    runs-on: ubuntu-latest
    steps:
      - run: echo "working directory is ${{ inputs.working_directory }}"
  publish-content:
    needs: draft-content
    runs-on: ubuntu-latest
    environment: human-approval-required
    steps:
      - run: echo "Publishing"
