name: Minimal Reusable
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      script_command:
        required: true
        type: string
      commit_message:
        required: true
        type: string
      file_pattern:
        required: true
        type: string
jobs:
  draft-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install dependencies
        run: |
          cd ${{ inputs.working_directory }}
          pip install -r requirements.txt
      - name: Run script
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          cd ${{ inputs.working_directory }}
          ${{ inputs.script_command }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: draft-content
          path: ${{ inputs.working_directory }}/${{ inputs.file_pattern }}

  publish-content:
    needs: draft-content
    runs-on: ubuntu-latest
    environment: human-approval-required
    permissions:
      contents: write
      issues: write
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Download draft content
        uses: actions/download-artifact@v4
        with:
          name: draft-content
          path: ${{ inputs.working_directory }}
      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.commit_message }}
          file_pattern: ${{ inputs.file_pattern }}
